### ISSUE TITLE
Tool stuck on the deploy C2 step

### ISSUE THREAD

**Issue by 0xblank** [ip2root/ip2root#65]
The tool is stuck at the C2 container deployment step, image is pulled, container is running but nothing happens

**Comment by Steels03** [comment]
Details ? Logs ? Ty @0xblank

**Comment by 0xblank** [comment]
Docker logs ?
The tool is just stuck at `[+] Deploying C2 container` forever

**Comment by 0xblank** [comment]
Fixed in last dev commit 34657858a72a718924830e8b34f2ad4b5114a9ac
